@startuml domain_model
    skinparam classAttributeIconSize 0
    skinparam style strictuml


    class " **TreeData** " as TD <<type>> {

    }

    class " **Reader** " as R <<type>> {

    }

    class "**Displayer**" as D <<type>> {

    }
 
    class "**Tree**" as T <<type>>{
        + LoadData()
        + CloseData()
    }

    class "**TreeView**" as TV <<type>> {

    }

    TD " * " --right-- R: reads < 
    R --right-- T: passes content >
    R --right-- T: instructs <
    T --right-- D: updates >
    D -right- TV: updates >


@enduml